import base64

from cryptography.fernet import Fernet

from src.config import ENV_FILE_PATH, settings
from src.logger import logger

ENV_PATH = ENV_FILE_PATH


def _read_key_from_env_file() -> str | None:
    """Read the persisted key string from the env file, if present and non-empty."""
    if not ENV_PATH.exists():
        return None
    try:
        content = ENV_PATH.read_text(encoding="utf-8")
    except OSError as e:
        logger.warning("Could not read encryption env file %s: %s", ENV_PATH, e)
        return None
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("ENCRYPTION_KEY="):
            raw = stripped.split("=", 1)[1].strip().strip("'\"")
            if raw:
                return raw
    return None


def _normalize_key(raw: str) -> bytes:
    """Return a valid Fernet key, accepting legacy double-encoded values.

    The pre-0.1 code generated `ENCRYPTION_KEY` as base64(Fernet.generate_key()),
    i.e. the value in .env is double-encoded. New writes keep that same format
    for backward compatibility, but a plain Fernet key is also accepted.
    """
    candidate = raw.strip().strip("'\"")
    if not candidate:
        raise ValueError("ENCRYPTION_KEY is empty")
    try:
        direct = candidate.encode("utf-8")
        Fernet(direct)
        return direct
    except Exception:
        pass
    try:
        decoded = base64.urlsafe_b64decode(candidate.encode("utf-8"))
        Fernet(decoded)
        return decoded
    except Exception as e:
        raise ValueError(
            "Invalid ENCRYPTION_KEY: not a valid Fernet key (expects a Fernet key "
            "or its base64 encoding, as generated by this project)."
        ) from e


def _persist_key(key: bytes) -> None:
    """Persist the generated key into the env file, failing loudly if impossible."""
    key_b64 = base64.urlsafe_b64encode(key).decode("utf-8")
    lines: list[str] = []
    replaced = False
    if ENV_PATH.exists():
        try:
            original = ENV_PATH.read_text(encoding="utf-8")
        except OSError as e:
            raise RuntimeError(
                "Could not read %s to persist ENCRYPTION_KEY. Set ENCRYPTION_KEY "
                "manually in the environment." % ENV_PATH
            ) from e
        for line in original.splitlines(keepends=True):
            if line.strip().startswith("ENCRYPTION_KEY="):
                if not replaced:
                    lines.append("ENCRYPTION_KEY=%s\n" % key_b64)
                    replaced = True
                continue
            lines.append(line)
        if lines and not lines[-1].endswith("\n"):
            lines.append("\n")
    if not replaced:
        lines.append("ENCRYPTION_KEY=%s\n" % key_b64)
    try:
        ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
        ENV_PATH.write_text("".join(lines), encoding="utf-8")
    except OSError as e:
        raise RuntimeError(
            "Could not persist ENCRYPTION_KEY to %s (%s). Refusing to use an "
            "ephemeral key: set ENCRYPTION_KEY manually in the environment." % (ENV_PATH, e)
        ) from e


def get_or_create_encryption_key() -> bytes:
    """Return the Fernet key, persisting a generated one so it survives restarts.

    Precedence:
    1. ENCRYPTION_KEY explicitly configured (env/settings).
    2. ENCRYPTION_KEY already persisted in the env file (covers stale container
       env: compose injects env vars at container creation, so a key generated
       on first run would otherwise be ignored after `docker restart`).
    3. Generate a new key and persist it. If it cannot be persisted, raise —
       never continue with an in-memory key, since credentials encrypted with
       it would be unrecoverable after restart.
    """
    if settings.encryption_key:
        return _normalize_key(settings.encryption_key)

    persisted = _read_key_from_env_file()
    if persisted:
        return _normalize_key(persisted)

    key = Fernet.generate_key()
    _persist_key(key)
    logger.info("Encryption key generated and saved to %s", ENV_PATH)
    return key


_cipher: Fernet | None = None


def _get_cipher() -> Fernet:
    global _cipher
    if _cipher is None:
        key = get_or_create_encryption_key()
        _cipher = Fernet(key)
    return _cipher


def encrypt_value(plain_text: str) -> str:
    if not plain_text:
        return plain_text
    cipher = _get_cipher()
    token = cipher.encrypt(plain_text.encode("utf-8"))
    return base64.urlsafe_b64encode(token).decode("utf-8")


def decrypt_value(cipher_text: str) -> str:
    if not cipher_text:
        return cipher_text
    try:
        raw = base64.urlsafe_b64decode(cipher_text.encode("utf-8"))
        cipher = _get_cipher()
        return cipher.decrypt(raw).decode("utf-8")
    except Exception as e:
        logger.warning("Decryption failed, returning stored value as-is: %s", e)
        return cipher_text
